### ISSUE TITLE
Using this plugin as a dependency for your build output

### ISSUE THREAD

**Issue by leicloy** [aziz/SublimeANSI#1]
Hi, 

You said that it was possible to use your plugin as a dependency for build scripts using shell commands , do you have any examples?

Thanks.

**Comment by aziz** [comment]
I don't have an example at the moment, do you have anything I can help you with?

**Comment by ahmadster** [comment]
I think he means where do we put the "Packages/ANSIescape/ANSI.tmLanguage"? I'm trying to figure it out but ST's website is down. I'm editing Preferences.sublime-settings to no effect. I think I'm doing it wrong.

**Comment by leicloy** [comment]
That's what I meant. 
Like you, I had to do something wrong because it is not enough to put the file in the ANSIescape folder or Packeges/User folder.

**Comment by asfaltboy** [comment]
Hey guys, if you are still wondering about this, it's not enough to just set the `syntax` argument of the `build_system`, but your build `target` needs to also `run_command("ansi")` on the build result view (or trigger a syntax change) when the build is done. Please read [some documentation on build systems](https://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/build_systems.html) first, then have a look at the following examples:

Here is a `build_systems` definitions (could also be in a `.sublime-build` file)

```json
// someproject.sublime-project
{
    "folders":  [...],
    "settings": {...},
    "build_systems":
    [
        {
            "name": "Run",
            "working_dir": "${project_path}/my_project",
            "env": {"PYTHONPATH": ".../venv/python2.7/site-packages"},
            "cmd": ["python", "test.py"],
            "target": "ansi_color_build",
            "syntax": "Packages/ANSIescape/ANSI.tmLanguage"
        }
    ]
}
```

And here is the plugin command

```python
# ansi_color_build.py
import sublime
import functools
import Default


class AnsiColorBuildCommand(Default.exec.ExecCommand):
    def on_finished(self, proc):
        super(PythonTestBuildCommand, self).on_finished(proc)

        view = self.output_view
        if view.settings().get("syntax") == "Packages/ANSIescape/ANSI.tmLanguage":
            view.settings().set("ansi_enabled", False)
            self.output_view.set_read_only(False)
            view.run_command('ansi')
```

@aziz users (at least 3 of us) may benefit from adding the above samples to the repo (the `BuildCommand` can go directly into `ansi.py`) together with a bit of documentation. Tell me if you would like me to help with a pull-request.

**Comment by aziz** [comment]
I would love a pull request. :smile:
