### ISSUE TITLE
no color

### ISSUE THREAD

**Issue by Emresav** [aziz/SublimeANSI#10]
Hello, 

I am running ANSI syntax/color scheme. weird ANSI escape codes disappeared but the text color did not change. I did not change anything in default ansi.sublime-settings.
 Any idea what the problem could be?

Thanks, 
Emre

**Comment by matt1003** [comment]
@Emresav When you change the syntax back to Plain Text do the ANSI escape reappear?

**Comment by matt1003** [comment]
@Emresav When you change the syntax back to Plain Text do the ansi escape code reappear? If so, try closing and re-opening the file; this should restore the escape codes therefore resolving the problem.

**Comment by Emresav** [comment]
fixed it. it is all because of a zero in my escape coded file. i.e.: [01;33m, but in your settings it is [1;33m.. thanks
