### ISSUE TITLE
Large file takes long time to load

### ISSUE THREAD

**Issue by KjellMorgenstern** [aziz/SublimeANSI#31]
A large file (~34MB) takes a minute to load. At first glance it looks like SublimeANSI is broken, especially if you have not used it before. 
Sublime Text is blocked, the OS X busy cursor is shown, and Sublime Text is marked "not responding" by OS X.

To reproduce
1. Open a ~34MB logfile, eg. from a rails project, <railsprojekt>/log/test.log, but probably any large ansi file will do
2. File is loaded fine by sublime text, no issues
3. Switch to ANSI: View -> Syntax -> ANSI
4. Sublime text is blocked, disc activity, takes 40-60 seconds to finish

Expected: Dealing with large ANSI files should not be much slower than for example SQL files. The same file, which also contains lots of SQL statements, works smooth when viewed with "View -> Syntax -> SQL", there is no notable loading time. Trying to parse it as C++ takes a few seconds.

**Comment by jfcherng** [comment]
Filled by https://github.com/aziz/SublimeANSI/pull/45
