### ISSUE TITLE
Crashes with large files

### ISSUE THREAD

**Issue by kfiducia** [aziz/SublimeANSI#42]
Changing to ANSI on large files crashes ST3, might just be worth indicating the upper limit on file size in documentation, still a very useful tool. Thanks.

**Comment by xanview** [comment]
Opened an 8MB file (which opens instantly without this plugin) and Sublime has been frozen for minutes now :(

**Comment by jfcherng** [comment]
@xanview Could you provide your exact test case if it's okay to be public?

**Comment by xanview** [comment]
Hi of course, attached.
[development.log](https://github.com/aziz/SublimeANSI/files/1482845/development.log)

**Comment by jfcherng** [comment]
@xanview Your test case could be rendered in about 4 seconds on my laptop with [this patch](https://github.com/aziz/SublimeANSI/pull/45).

**Comment by lm1baker** [comment]
Confirm a large improvement from your patch, I have a 100 000 line file that takes about four minutes with the package control version of the plugin, with the above patch, parsing the file takes about 4 seconds.
