### ISSUE TITLE
Coloring gone

### ISSUE THREAD

**Issue by Zlatov** [aziz/SublimeANSI#62]
Coloring of the text disappeared. Ubuntu-18, ST-3207. Previously worked. After installing manually and switching to commit b97ea0ea077181c7b8cb9db6d8a2775b2541ea6c the problem disappears. Tested on two computers at home and at work. I would like to get rid of manual rollback of the package.

**Comment by jfcherng** [comment]
Without a exact reproducer, I do not think there is something that I can do to help you. b97ea0ea077181c7b8cb9db6d8a2775b2541ea6c is not helpful here.

**Comment by jfcherng** [comment]
Does this work for you?
https://github.com/aziz/SublimeANSI/commit/d9c7fc6b1e0dd4431eee1c7fec2aadde754c7346

**Comment by NicoLugil** [comment]
I just installed ANSIEscape, I also get no colours:

![image](https://user-images.githubusercontent.com/5839206/66115751-c9518800-e5d1-11e9-91c5-94de2a260556.png)

**Comment by jfcherng** [comment]
@NicoLugil ANSIEscape is not auto working. You have to set syntax for it.

**Comment by NicoLugil** [comment]
Yes it is set:

![image](https://user-images.githubusercontent.com/5839206/66123677-e80c4a80-e5e2-11e9-8d06-6223f3859319.png)

**Comment by jfcherng** [comment]
Upload the original text here so people can reproduce it.

**Comment by NicoLugil** [comment]
This is the text:

```
[^[[34m2019-10-03T14:08:38^[[0m] DEBUG ^[[36mCSettings^[[0m: ^[[35mReading settings file ^[[0m
[^[[34m2019-10-03T14:08:38^[[0m] DEBUG ^[[36mCSettings^[[0m: ^[[35m------------------------ matching ---------------------^[[0m
[^[[34m2019-10-03T14:08:38^[[0m] DEBUG ^[[36mCSettings^[[0m: ^[[35mpattern is >playground<^[[0m
```
renders as follows on my terminal:

![image](https://user-images.githubusercontent.com/5839206/66134236-468ff380-e5f8-11e9-99fd-ff3fe3f86d9b.png)

**Comment by NicoLugil** [comment]
Can I see from within sublime which version I am using?

**Comment by jfcherng** [comment]
Yes. `Ctrl+P` -> type `package list`

**Comment by jfcherng** [comment]
> This is the text:
> 
> ```
> [^[[34m2019-10-03T14:08:38^[[0m] DEBUG ^[[36mCSettings^[[0m: ^[[35mReading settings file ^[[0m
> [^[[34m2019-10-03T14:08:38^[[0m] DEBUG ^[[36mCSettings^[[0m: ^[[35m------------------------ matching ---------------------^[[0m
> [^[[34m2019-10-03T14:08:38^[[0m] DEBUG ^[[36mCSettings^[[0m: ^[[35mpattern is >playground<^[[0m
> ```
> 
> renders as follows on my terminal:
> 
> ![image](https://user-images.githubusercontent.com/5839206/66134236-468ff380-e5f8-11e9-99fd-ff3fe3f86d9b.png)

please upload a file. github wont be exact the same for some invisible chars.

**Comment by NicoLugil** [comment]
[sf.log](https://github.com/aziz/SublimeANSI/files/3686779/sf.log)

**Comment by NicoLugil** [comment]
version:
![image](https://user-images.githubusercontent.com/5839206/66140064-bf477d80-e601-11e9-9f83-5c34fdec8b0a.png)

**Comment by jfcherng** [comment]
> [sf.log](https://github.com/aziz/SublimeANSI/files/3686779/sf.log)

This file works on my side.
![image](https://user-images.githubusercontent.com/6594915/66141651-9db4b900-e636-11e9-9563-8b06bd7b279a.png)

- What version of ST you are using?
- What's the plugin settings for `ANSIescape`?

**Comment by Zlatov** [comment]
After f2bdf3985f90a98aba4e22c7672daa0248f99b8f works fine!
But, which is more correct?:
```json
  // ~/.config/sublime-text-3/Packages/User/builds/Bash.sublime-build

  "syntax": "Packages/ANSIescape/ANSI.tmLanguage",
  // or
  "syntax": "Packages/ANSIescape/ANSI.sublime-syntax"
```

**Comment by jfcherng** [comment]
> After [f2bdf39](https://github.com/aziz/SublimeANSI/commit/f2bdf3985f90a98aba4e22c7672daa0248f99b8f) works fine!
> But, which is more correct?:
> 
> ```json
>   // ~/.config/sublime-text-3/Packages/User/builds/Bash.sublime-build
> 
>   "syntax": "Packages/ANSIescape/ANSI.tmLanguage",
>   // or
>   "syntax": "Packages/ANSIescape/ANSI.sublime-syntax"
> ```

The later one. It's a newer syntax format for ST.
