### ISSUE TITLE
Error loading colour scheme in Windows

### ISSUE THREAD

**Issue by emiltin** [aziz/SublimeANSI#63]
After installing with Package Control, I get this error:

Error loading colour scheme
Packages/User/ANSIescape/tmTheme: Unable to open Packages/User/ANSIescape/tmTheme

Looking in the folder Packages/User/ there is a file named 'ansi'. Inspecting it shows it really has the name 'ansi.sublime-colour-schema'.

I'm using SublimeText 3.0, build 3143 in Windows.

**Comment by jfcherng** [comment]
should've been fixed in 0.3.6
