### ISSUE TITLE
Missing theme file in Sublime Text 4 (Linux)

### ISSUE THREAD

**Issue by malaire** [aziz/SublimeANSI#65]
After installing ANSIescape from Package Control and trying to set filetype to ANSI I get this error:

> Error loading colour scheme Packages/User/ANSIescape/ansi.tmTheme: Unable to open Packages/User/ANSIescape/ansi.tmTheme

The directory `Packages/User/ANSIescape` exists but is empty.

Version: Sublime Text 4, build 4107
OS: Debian Stable

**Comment by jfcherng** [comment]
Should've been fixed in 0.3.6. The [Terminus](https://packagecontrol.io/packages/Terminus) plugin is recommended nowadays though.

**Comment by malaire** [comment]
But Terminus seems to be just a terminal, and doesn't seem to support showing ANSI files?

**Comment by jfcherng** [comment]
> But Terminus seems to be just a terminal, and doesn't seem to support showing ANSI files?

If you `cat` the ANSI file, maybe it will work but I am not sure.

**Comment by malaire** [comment]
This is not fixed in 0.3.6, error message just changes to

> Error loading colour scheme Packages/User/ANSIescape/ansi.sublime-color-scheme: Unable to open Packages/User/ANSIescape/ansi.sublime-color-scheme

**Comment by jfcherng** [comment]
Any other errors in the console, after ST restart?

**Comment by malaire** [comment]
No other errors and after ST restart that error above goes away, but colors still doesn't work. I just get white text on black, with color codes hidden.

**Comment by jfcherng** [comment]
Could you provide an example file?

**Comment by malaire** [comment]
Here's example file:
[cargo-asm.txt](https://github.com/aziz/SublimeANSI/files/6584783/cargo-asm.txt)

**Comment by jfcherng** [comment]
Okay, that's because this plugin only supports 3/4-bit colors.
https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit

This plugin literally generate all possible combination of colors in the ANSI color scheme. 8-bit colors have too many possible permutations.

**Comment by malaire** [comment]
ok, I got it working by pre-processing the file to use correct color codes.

I noticed that the file actually does use only 3/4-bit color codes, it just uses the longer format, e.g. `ESC[38;5;9` instead of `ESC[91`.

It would be nice if you could support also longer format for the basic colors, but that's not essential for me as I can pre-process the file as needed.

**Comment by jfcherng** [comment]
I actually don't use this plugin now...
