### ISSUE TITLE
Unable to find Packages/User/ANSIescape/ansi.sublime-color-scheme

### ISSUE THREAD

**Issue by SalvatoreT** [aziz/SublimeANSI#66]
When I select the ANSI language, I get the following error.

```
Error loading colour scheme Packages/User/ANSIescape/ansi.sublime-color-scheme: Unable to find Packages/User/ANSIescape/ansi.sublime-color-scheme
```

<img width="675" alt="Screen Shot 2021-06-10 at 4 48 52 PM" src="https://user-images.githubusercontent.com/1223008/121610923-f6dc0f00-ca0b-11eb-9c26-d8f29b300364.png">

I'm on ANSIescape version `0.6.3` and Sublime Text 4 (build 4107).

<img width="675" alt="Screen Shot 2021-06-10 at 4 48 30 PM" src="https://user-images.githubusercontent.com/1223008/121610958-0c513900-ca0c-11eb-82c6-df5ddee8ef41.png">

**Comment by jfcherng** [comment]
restart ST.

**Comment by SalvatoreT** [comment]
That fixed it! Thank you. 🙌🏼
