### ISSUE TITLE
Error loading colour scheme

### ISSUE THREAD

**Issue by Gerst20051** [aziz/SublimeANSI#67]
I get this error when I try to set the syntax to "ANSI". `Error loading colour scheme Packages/User/ANSIescape/ansi.sublime-color-scheme: Unable to find Packages/User/ANSIescape/ansi.sublime-color-scheme`

After looking through the closed issues it looks like restarting sublime might fix it: https://github.com/aziz/SublimeANSI/issues/66#issuecomment-859166222

**Comment by jfcherng** [comment]
Should've been fixed via cb42936e7c8ae5983e0d6a913f9081fb50bbd0b3
